### ISSUE TITLE
Feature request: SSH Agent forwarding

### ISSUE THREAD

**Issue by Tycho-S** [open-keychain/termbot#11]
Thanks for writing TermBot!! It's so great to be finally able to use yubikeys for SSH authentication on Android.

Just one feature request: Could you add a feature to forward the authentication token as a (virtual) SSH agent? I use the agent forwarding a lot, and on Linux I can forward the Yubikey this way (because gnupg-agent works as an SSH agent). It would be great to be able to do the same with TermBot.

**Comment by hagau** [comment]
Thanks!
This should already work, I just did a rudimentary test.
Enable the '*Use SSH auth agent*' switch in the host config.
(I need to rename that option to clarify that agent forwarding is meant)
@TychoSchenkeveld is this working as intented for you?

**Comment by Tycho-S** [comment]
Thanks for your quick reply!

When I switch that on, it does provide an agent socket to the server I'm connecting to. But it's not offering any keys (ssh-add -l returns no identities). I was hoping it would offer the key I'm connecting with. It's a Yubikey, by the way (connected over USB).

I had checked this before submitting the request, but I just noticed that it didn't work. I didn't see it actually provides a socket to the other side. Nice!! So it looks like the code is there, it just doesn't pick up my token somehow.

**Comment by hagau** [comment]
Ok, I'll setup a test environment for this and investigate.

**Comment by Tycho-S** [comment]
Thank you! I'd really appreciate it! Let me know if I can provide any info.

**Comment by laseryuan** [comment]
+1

**Comment by alexdetsch** [comment]
+1

**Comment by snapp** [comment]
+1

**Comment by alex005005** [comment]
+1 I use it to authorize sudo.

PS: I was thrilled to see this app. Keep up the good work!

PPS: Couldn't get it from F-Droid though. Something about incompatible signatures. Had to spin up Play Store.

**Comment by Tycho-S** [comment]
> +1 I use it to authorize sudo.

Yes me too :) With pam_ssh_agent_auth ( https://github.com/jbeverly/pam_ssh_agent_auth ) . Works great, it would be super if this would be available in termbot. For now I have set an OATH token ("Google authenticator" type idea using pam_oath, https://www.nongnu.org/oath-toolkit/pam_oath.html ) as alternative so I can type the key over the SSH session.

**Comment by alex005005** [comment]
@hagau, did you figure out what's going wrong?

**Comment by hagau** [comment]
@alex005005 sorry for the late reply. Agent forwarding is not fully implemented and I couldn't find the time for it yet. I'll look into this some more soonish :)

**Comment by lucaszc** [comment]
+1 agent forward is a feature extremely  important with smartcards, yubico and etc ...

**Comment by iprok** [comment]
@hagau Thanks for your job! +1 to users who needs the feature. May be we can speed up the process with some sponsoring?

**Comment by Tycho-S** [comment]
Good idea! I can contribute as well.

**Comment by lucaszc** [comment]
Any progress in this feature using COTECH SDK ?

**Comment by dschuermann** [comment]
For now we focused on getting TermBot to work without OpenKeychain which makes it a lot easier to use for novice.
Please report new issues and features requests at https://github.com/cotechde/termbot

**Comment by Tycho-S** [comment]
Can you still use it with OpenKeychain though? I need that because I use OKC for more than just Termbot.

**Comment by dschuermann** [comment]
> Can you still use it with OpenKeychain though? I need that because I use OKC for more than just Termbot.

It should have the same functionality as before, it simply no longer requires OpenKeychain, because this functionality is now integrated directly into TermBot. Maybe our FAQ helps: https://hwsecurity.dev/termbot/#faq

Are you missing a feature?

**Comment by Tycho-S** [comment]
> > Can you still use it with OpenKeychain though? I need that because I use OKC for more than just Termbot.
> 
> It should have the same functionality as before, it simply no longer requires OpenKeychain, because this functionality is now integrated directly into TermBot. Maybe our FAQ helps: https://hwsecurity.dev/termbot/#faq
> 
> Are you missing a feature?

Ah I didn't use it in the last few days, did you update it recently? If it doesn't stop OKC from working it should be OK :) I use Fidesmo cards as well as Yubikeys though and I don't see the Fidesmo's in your list. However they're just OpenPGP over NFC so they should work fine, I'll let you know.

But the agent forwarding would still be really great to have if it is possible in the future. It's the only thing I'm really missing in the old one.

**Comment by dschuermann** [comment]
> Ah I didn't use it in the last few days, did you update it recently? If it doesn't stop OKC from working it should be OK :) I use Fidesmo cards as well as Yubikeys though and I don't see the Fidesmo's in your list. However they're just OpenPGP over NFC so they should work fine, I'll let you know.

Yep, there is a new update :)

Fidesmo cards should work without issues. You just need to add the cards/YubiKeys into TermBot as described here: https://hwsecurity.dev/termbot/#faq

You can still manage the cards/YubiKeys using OpenKeychain. They should work in both apps without issues.

> But the agent forwarding would still be really great to have if it is possible in the future. It's the only thing I'm really missing in the old one.

Yep, let's see what we can do.

**Comment by Tycho-S** [comment]
You're right, it works fine, just tried it. It sees the Fidesmo as a Yubikey.

I like the way I can add cards now without having the public key (in OKC you have to load the public key from a file or the keyserver, because it's the full PGP data is not on the smart card).

One thing I miss though is not being able to rename the keys (They're all Yubikey and a number). I give them all names, but I'll put in a feature request in the other repo. Thanks!

**Comment by dschuermann** [comment]
> You're right, it works fine, just tried it. It sees the Fidesmo as a Yubikey.
> 
> I like the way I can add cards now without having the public key (in OKC you have to load the public key from a file or the keyserver, because it's the full PGP data is not on the smart card).

Yep, exactly. Should be much easier now :)
 
> One thing I miss though is not being able to rename the keys (They're all Yubikey and a number). I give them all names, but I'll put in a feature request in the other repo. Thanks!

The number is acually the serial number, you can compare it with the number printed on a YubiKey. Regarding Fidesmo: Looks like they didn't change the vendor ID in their Yubikey-NEO fork, thus it is detected as Yubikey.

**Comment by Tycho-S** [comment]
> > One thing I miss though is not being able to rename the keys (They're all Yubikey and a number). I give them all names, but I'll put in a feature request in the other repo. Thanks!
> 
> The number is acually the serial number, you can compare it with the number printed on a YubiKey. Regarding Fidesmo: Looks like they didn't change the vendor ID in their Yubikey-NEO fork, thus it is detected as Yubikey.

I know, it's just different than the names I give them :) Also, the Fidesmo cards don't report their number correctly. There's a number printed on the card but they all show up as "00090001". Probably something broken in their applet but it wasn't an issue before because I gave them a different name. Anyway I raised a request for it, I understand you may not have time to look at it. No worries.

PS Opened a ticket in the new repo too for the agent fwd so it can be tracked - I saw there were more people looking for it so it'd be raised sooner or later. Hope you don't mind!

**Comment by therealpxc** [comment]
Edit: I had a few issues open in various tabs and didn't realize the linked issue above was to the new Termbot repo, thinking it was for a related issue in another project. Seeing that the releases here had been outpaced on the Play Store, I thought maybe this app had changed license.

That was an embarrassing mixup for me. :flushed:

**Comment by dschuermann** [comment]
The app is not proprietary, but this is the old repository. Please go to https://github.com/cotechde/termbot.
Regarding the releases: Again, I am confused by your statement, the newest version on Fdroid and Google Play is 1.9.5-termbot8 and can be found here: https://github.com/cotechde/termbot
SSH agent forwarding it still not implemented.

**Comment by dschuermann** [comment]
Closing. Issues for current release are tracked here: https://github.com/cotechde/termbot/issues

**Comment by therealpxc** [comment]
Oh, I'm so sorry. Thanks for correcting my misunderstanding. I didn't realize the repo had moved.
