### ISSUE TITLE
Feature Request: GPG Agent Forwarding

### ISSUE THREAD

**Issue by snapp** [open-keychain/termbot#13]
First, I'm so stoked to finally have my Yubikey working on my Android device; Thanks very much!

In addition to running into the same issue reported in feature request #11, I'm also hoping to be able to access my signing and encryption subkeys from my yubikey via GPG Agent forwarding.

I currently make heavy use of this on my laptop and am longing for a day where I don't need to lug that machine around and simply rely on my phone.

Is this capability already available and I'm just not seeing how to enable it?

Thanks again!

**Comment by hagau** [comment]
No, this is not available yet, but it would be a nice feature.
- This will need #11.
- Termbot needs to implement OpenKeychain's `openpgp-api`

**Comment by dschuermann** [comment]
Closing. Issues for current release are tracked here: https://github.com/cotechde/termbot/issues
