### ISSUE TITLE
Feature Request: SSH Jump Host

### ISSUE THREAD

**Issue by snapp** [open-keychain/termbot#14]
I may simply be missing how to configure this, but I'm trying to set termbot up with a bastion host that the rest of my host connections would reference as their SSH jump host.

In the past I've used JuiceSSH that allows for this type of configuration to the point where I can actually setup the multiple levels of jump hosts required for some of my more restricted machines.

Is this capability already available and I just haven't discovered it yet?

Thanks!

**Comment by snapp** [comment]
FWIW, if this request, #11, and #13 ended up being achievable, I'd finally have everything I needed for my day-to-day workflow to be doable within Android.

**Comment by hagau** [comment]
Hm, there is no explicit support for jump hosts yet, but one could setup an automatic command (*"Post-login automation"*) to be run on login to ssh into the next hop.  
Of course, proper support would be nice...

**Comment by dschuermann** [comment]
Closing. Issues for current release are tracked here: https://github.com/cotechde/termbot/issues
