### ISSUE TITLE
Feature Request: Duplicate hosts

### ISSUE THREAD

**Issue by Vashiru** [open-keychain/termbot#15]
I have a few servers that require the same type of SSH setup, apart from the name and the IP-address. Having to manually enter and check the settings for each of them is a bit of a pain. It would be nice if you could duplicate existing hosts and then edit them (maybe even directly open the edit window and have a toast notification say "host duplicated").

**Comment by dschuermann** [comment]
Closing. Issues for current release are tracked here: https://github.com/cotechde/termbot/issues
