### ISSUE TITLE
bug: special keys not available.

### ISSUE THREAD

**Issue by ghost** [open-keychain/termbot#16]
### Expected behavior:
Special keys are drawn above the primary keyboard, since `Always show additional keys` setting is on.

### Actual behavior:
Special keys not showing up.

**Comment by hagau** [comment]
I can't replicate this, do you have more details? Also, there's no `Always show additional keys` setting, it's `Special keys always visible`.

**Comment by agherzan** [comment]
They are actually available but I suspect that they are covered by the keyboard. This is actually very annoying because the keyboard covers a lot of the ssh session. Is there any way we can resize when keyboard pops up?

**Comment by dschuermann** [comment]
Closing. Issues for current release are tracked here: https://github.com/cotechde/termbot/issues
