### ISSUE TITLE
bug: does not scroll automatically.

### ISSUE THREAD

**Issue by ghost** [open-keychain/termbot#17]
When the entire screen except keyboard is covered by text and another command is sent, the screen should automatically scroll down to show the result of the recent command, which is not the case.

**Comment by hagau** [comment]
I can't replicate this here, do you have any further information?

**Comment by ghost** [comment]
Is it possible to export all settings to some file?

**Comment by hagau** [comment]
No, that's not implemented at the moment.

**Comment by dschuermann** [comment]
Closing. Issues for current release are tracked here: https://github.com/cotechde/termbot/issues
