### ISSUE TITLE
Feature : option to disable connection notification

### ISSUE THREAD

**Issue by echto** [open-keychain/termbot#19]
Any chance we can get an option to turn off the notification sound when a connection is made?

**Comment by quanmqiu** [comment]
agreed, I turned off all notifications. but the sound can't been off.

**Comment by echto** [comment]
I submitted a code change to disable the sound when a connection is made.  Please see the link below for the request.

https://github.com/open-keychain/termbot/pull/25

quanmqiu - In the mean time, I compiled the modified source and uploaded the termbot apk here  https://file.io/HNaciw  It's available if you want to use it.  The filename is termbot-debug.apk.

sha256sum 
5d503f7def8867b0641a29de7a8ebc0eb5bf3d58c007ae56cc00d1a49c9ad4d3  termbot-debug.apk

**Comment by dschuermann** [comment]
Closing. Issues for current release are tracked here: https://github.com/cotechde/termbot/issues
