### ISSUE TITLE
Use external agent UI issues

### ISSUE THREAD

**Issue by wiktor-k** [open-keychain/termbot#2]
When editing a host when I select `Use external agent` a popup appears `Select agent` and immediately on top of it `Select authentication key` (I didn't press anything!). When I select a key and press Select to dismiss that window I see `Select Agent` window. When I press OpenKeychain there I see `Select authentication key` window again. That's clearly wrong as `Select authentication key` should only appear after `Select Agent` is dismissed.

I can provide screenshots but the UI bug depends on time (two windows opened at the same time).

Also there is a toggle `Use SSH agent for authentication` below `Encoding` that I think does nothing, toggling it and saving has no effect.

TermBot version: 1.9.2.

**Comment by hagau** [comment]
Thanks for the report!

This happens when only one agent is installed, which of course was not my test configuration...

Fixed in 72cc86e539e516f0c5c850b9aeae559b741aa52e

**Comment by dschuermann** [comment]
Released as 1.9.2-termbot.1

**Comment by hagau** [comment]
@wiktor-k 
The "Use SSH auth agent" toggle is for auth agent forwarding. That was already in upstream.

**Comment by wiktor-k** [comment]
@hagau thank you for a quick fix, now it's working as expected, I mean the UI :)
Auth agent forwarding is not being saved here, but I'll test that and report another issue if I find it defective.
