### ISSUE TITLE
Feature request: mosh support

### ISSUE THREAD

**Issue by rmopl** [open-keychain/termbot#22]
Is [mosh](https://mosh.org/) support planned or considered? 

It's great for roaming and high latency links. Plus there used to be a [connectbot version with mosh support](https://dan.drown.org/android/mosh/).

**Comment by theftf** [comment]
Sounds greate :+1: 
It should be doable by porting thes two classes to termbot:
https://github.com/ddrown/irssiconnectbot/blob/master/src/org/woltage/irssiconnectbot/transport/Mosh.java
https://github.com/ddrown/irssiconnectbot/blob/master/src/org/woltage/irssiconnectbot/util/InstallMosh.java

I tryed and failed :( But i'm not a java developer.

**Comment by dschuermann** [comment]
Closing. Issues for current release are tracked here: https://github.com/cotechde/termbot/issues
