### ISSUE TITLE
alphanumeric smartcard pins not supported

### ISSUE THREAD

**Issue by demure** [open-keychain/termbot#28]
It appears that the recent version in the google play store (1.9.5-61-516a955-termbot) which no longer uses OpenKeychain does not support alphanumeric smartcard pins. Perhaps the pinentry menu should have a button to bring up a full keyboard so that those with non number based smartcard pins can use their keys.

**Comment by rwky** [comment]
It's also limited to 10 characters the buttons grey out after that which makes it unusable with longer pins.

**Comment by dschuermann** [comment]
Will answer here: https://github.com/cotechde/termbot/issues/1
