### ISSUE TITLE
Is Termbot still an open source software?

### ISSUE THREAD

**Issue by bungabunga** [open-keychain/termbot#29]
There's a 1.9.5 version on Play Store without any code change here for months. Is Termbot on Play Store still an open source project?

**Comment by dschuermann** [comment]
TermBot is now developed here: https://github.com/cotechde/termbot
We are working on it :)

**Comment by rekahsoft** [comment]
termbot used to include an integration for open-keycain. This appears to no longer be the case with the most recent version in f-droid. Now when I go to the "public keys" page, it prompts me to "Get the Hardware Security SDK", which appears to be proprietary. :sob:
