### ISSUE TITLE
The server hostkey was not accepted by the verifier callback. Unknown key type rsa-sha2-512

### ISSUE THREAD

**Issue by qirtaiba** [open-keychain/termbot#30]
Hello,

What do I do about the above error? I'm using termbot with a Yubikey to connect to a user account on a Debian 10 server. It works when connecting to a different server running Ubuntu 19.04.

Thanks.

**Comment by dschuermann** [comment]
Closing. Issues for current release are tracked here: https://github.com/cotechde/termbot/issues
